Portfolio: desktop version
kerlos-bahaa/Portfolio pull request #6
Opened 2023-03-29 22:19 UTC by kerlos-bahaa

-Add desktop first page
-Add desktop work section
-Add desktop about me section
-Add desktop contact me section

2023-03-29 23:28 UTC, tufoinnkuo10 requested changes
Hi @kerlos-bahaa 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ Responsive

Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/a6O5pzQ8pAPTCoeagK/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-03-29 23:28 UTC, tufoinnkuo10 commented on Index.html
> +    <link rel="stylesheet" href="Css/Deskto.css" media="(min-width: 768px) ">
- [ ] Great job setting the media query from here. Please remember the guidelines are to test and prepare you on some particular aspect, and on this you were to use media queries for the Desktop breakpoint in the CSS file. This was to see how you can differentiate the mobile and desktop in one CSS file. Please, you can use the other method later on. It was clearly mentioned in the project requirement for you as well 👇🏾 


![Screenshot (917)_LI](https://user-images.githubusercontent.com/65298048/228689872-fac3f1d6-23de-45d5-b1f5-431e5e661629.jpg)

2023-03-29 23:28 UTC, tufoinnkuo10 commented on Index.html
> +    <img class="pcrepeated-img" src="./picture/pc3.png" alt="">
- [ ] please add a little padding left and right to the desktop cards

2023-03-29 23:28 UTC, tufoinnkuo10 commented on Index.html
> +    <h2 class="About-name">About Myself</h2>
- [ ] please kindly add a little padding left to the about section so it matches the original design

![Screenshot (916)_LI](https://user-images.githubusercontent.com/65298048/228686323-8fa56acf-9235-4824-858b-171c617490e3.jpg)

2023-03-29 23:28 UTC, tufoinnkuo10 commented on Index.html
> +        <!-- contact me  -->
- [ ] please kindly use the correct background image in the desktop contact section like in the original design.
yours
![Screenshot (913)](https://user-images.githubusercontent.com/65298048/228685266-254b50ed-a951-41cc-ac4e-0de5569fbbb5.png)
figma
![Screenshot (914)](https://user-images.githubusercontent.com/65298048/228685289-a2f71027-aaa8-4326-b006-9a64f3193555.png)

2023-03-30 12:41 UTC, iambenkis approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @iambenkis in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 12:48 UTC, merged